FROM ruby:2.5.1
RUN apt-get update && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir /app
WORKDIR /app
ADD Gemfile /app/Gemfile
ADD Gemfile.lock /app/Gemfile.Lock
run bundle install 
ADD . /app